version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.871.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.878.0
    - 2.880.0
    - 2.882.0
    - 2.883.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.2
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
